### ISSUE TITLE
ClassCastException【bug】

### ISSUE THREAD

**Issue by maryZhao-nari** [InterPSS-Project/ipss-odm#11]
@thuang @jinjingfarm 
# org.ieee.odm.model.dstab.DStabParserHelper.getDefaultGen(BusGenDataXmlType genData)

**_bug_**:
java.lang.ClassCastException: org.ieee.odm.schema.LoadflowGenDataXmlType cannot be cast to org.ieee.odm.schema.DStabGenDataXmlType
    at org.ieee.odm.model.dstab.DStabParserHelper.getDefaultGen(DStabParserHelper.java:142)
    at org.ieee.odm.adapter.bpa.dynamic.BPADynamicGeneratorRecord.processGeneratorData(BPADynamicGeneratorRecord.java:166)
    at org.ieee.odm.adapter.bpa.dynamic.BPADynamicRecord.processDynamicData(BPADynamicRecord.java:62)
    at org.ieee.odm.adapter.bpa.BPAAdapter.parseInputFile(BPAAdapter.java:117)

**Comment by jinjingfarm** [comment]
@maryZhao-nari In the ipss-dom project, please do the following:

1) Create a new branch from the master branch, if you are working on the master branch

2) In the new branch, create a test/sample case to show the issue

3) Check-in the branch so that we can duplicate the issue.
