### ISSUE TITLE
Something went wrong when I try to input bpa format data

### ISSUE THREAD

**Issue by shichen164429350** [InterPSS-Project/ipss-odm#18]
In the case  ieee9 bus test,I changed the default psse format data into the bpa format data, but something went wrong: 
At first ,I want to use my own data  to finish my project, but it always went wrong, finally, I found that I cannot even   input the 07c-dc2load.dat and IEEE9.DAT, that's so terrible.
Can anyone help me ?Thanks!
/////////////////////////code//////////////////////////////
public class DStab_IEEE9Bus_Test {
	IPSSMsgHub msg = CoreCommonFactory.getIpssMsgHub();
	@Test
	public void test_IEEE9Bus_Dstab(){
		IpssCorePlugin.init();
		BPAAdapter adapter = new BPAAdapter();
		assertTrue(adapter.parseInputFile(NetType.DStabNet, new String[]{
				"testData/bpa/tegaoyatouchan/IEEE9.dat"
		}));
		DStabModelParser parser =(DStabModelParser) adapter.getModel();
//////////////////////////////////////////////////////////
error message :
二月 20, 2019 3:27:37 下午 org.ieee.odm.adapter.AbstractODMAdapter parseInputStream
严重: java.lang.ArrayIndexOutOfBoundsException: 1
java.lang.ArrayIndexOutOfBoundsException: 1
	at org.ieee.odm.adapter.bpa.BPAAdapter.parseInputFile(BPAAdapter.java:116)
	at org.ieee.odm.adapter.AbstractODMAdapter.parseInputFile(AbstractODMAdapter.java:234)
	at org.ieee.odm.adapter.AbstractODMAdapter.parseInputStream(AbstractODMAdapter.java:191)
	at org.ieee.odm.adapter.AbstractODMAdapter.parseInputFile(AbstractODMAdapter.java:215)
	at org.ieee.odm.adapter.AbstractODMAdapter.parseInputFile(AbstractODMAdapter.java:202)
	at org.interpss.tutorial.ch5_dstab.DStab_IEEE9Bus_Test.test_IEEE9Bus_Dstab(DStab_IEEE9Bus_Test.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:
////////////////////////////////////////////////////////

**Comment by shichen164429350** [comment]
The data  are as follows:
///////IEEE9.dat/////////
POWERFLOW,CASEID=IEEE9,PROJECT=IEEE_9BUS_TEST_SYSTEM)
/MVA_BASE=100\
/SOL_ITER,DECOUPLED=2,NEWTON=15,OPITM=0\
/P_OUTPUT_LIST,ZONES=ALL\
/RPT_SORT=ZONE\
/NEW_BASE,FILE=IEEE90.BSE\
/PF_MAP,FILE = IEEE90.MAP\
/NETWORK_DATA\
.A  NF        Gen1     16.5           01    
BS    Gen1    16.501                      999. 999.      1.01    
B     Bus1    230.01                  
B     BusA    230.01 125. 70.0     20.
BE     BusA    230.02              -84          
B     BusB    230.01  90. 40.0     10.    
B     BusC    230.01 100. 55.0     20.       
B     Bus2    230.01 35.0 10.0            
BE    Gen2    18.001                      163. 999       1.01
B     Bus3    230.01
BE    Gen3    13.801                       85. 999.      1.01
.L -----------------  transmission lines ----------------------------
L     Bus1    230. BusA    230.       .0100 .0850        .0440
L     Bus1    230. BusB    230.       .0170 .0920        .0395
L     BusA    230. Bus2    230.       .0320 .1610        .0765
L     BusB    230. Bus3    230.       .0390 .1700        .0895
L     Bus2    230. BusC    230.       .0085 .0720       .03725
L     BusC    230. Bus3    230.       .0119 .1008       .05225
.T ----- transformers ---------
T     Gen1    16.5 Bus1    230.             .0567             16.5 242. 
T     Gen2    18.0 Bus2    230.             .0625             18.0 242. 
T     Gen3    13.8 Bus3    230.             .0586             13.8 242. 
(END)
